# Generated by Django 6.0.3 on 2026-03-31 18:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=180)),
                ('description', models.TextField()),
                ('assignment_type', models.CharField(choices=[('tp', 'TP'), ('td', 'TD'), ('homework', 'Homework'), ('project', 'Project')], max_length=20)),
                ('submission_mode', models.CharField(choices=[('individual', 'Individual'), ('duo', 'Duo'), ('group', 'Group')], max_length=20)),
                ('max_score', models.DecimalField(decimal_places=2, default=20, max_digits=6)),
                ('open_at', models.DateTimeField()),
                ('due_at', models.DateTimeField()),
                ('allow_late', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.course')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='accounts.professorprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='assignments.assignment')),
                ('leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_groups', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudyGroupMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='assignments.studygroup')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to='accounts.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('late', 'Late'), ('graded', 'Graded'), ('returned', 'Returned')], default='submitted', max_length=20)),
                ('content_text', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='submissions/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.assignment')),
                ('graded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to='accounts.professorprofile')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.studygroup')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='individual_submissions', to='accounts.studentprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='studygroup',
            constraint=models.UniqueConstraint(fields=('assignment', 'name'), name='uniq_group_name_per_assignment'),
        ),
        migrations.AddConstraint(
            model_name='studygroupmember',
            constraint=models.UniqueConstraint(fields=('group', 'student'), name='uniq_group_student'),
        ),
    ]
